
(define (parse exp)
  (display (format "parse: ~A ~%" exp))
  (cond ((number? exp) (make-number-value exp))
		((string? exp) (make-string-value exp))
		((symbol? exp) (make-variable exp))
		((tagged-list? exp 'quote)  (make-quotation exp))
		((tagged-list? exp 'set!)   (make-assginment exp))
		((tagged-list? exp 'define) (make-definition exp))
		((tagged-list? exp 'if)     (make-if exp))
		((tagged-list? exp 'lambda) (make-lambda exp))
		((tagged-list? exp 'begin)  (make-sequence exp))
		((pair? exp) (make-application exp))
		(else
		 (error "parse: unknown expression: " exp))))
